ballista-compute/ballista

build-docker-image.sh, docker/Dockerfile.binary, docker/Dockerfile.platform, examples/nyctaxi/Dockerfile, examples/nyctaxi/build-docker-image.sh
Holy crap this actually works!  There are a few hacks, but overall I think it'll scale pretty well. At least until Cargo implements their `build-deps` verb. 
closes #15
=> refactored dockerfile to make caches work 

.travis.yml, src/bin/cli.rs, src/bin/server.rs, src/cluster.rs, src/execution.rs, src/lib.rs, tests/plan_serde.rs
Cleaned a couple of things up as I was going through
Could add a test on these too
=> Cargo fmt & clippy

src/client.rs
I noticed a TODO in client.rs and thought it was a nice easy change. I've tested that it works by rerunning the NYC taxis example.
=> Use channel to send results back from executor to client

src/lib.rs
=> Re-export arrow and datafusion from crate root

jvm/examples/src/main/kotlin/ParallelQuery.kt, jvm/logical-plan/src/main/kotlin/Expressions.kt, jvm/physical-plan/src/main/kotlin/Expressions.kt, jvm/sql/src/main/kotlin/Expressions.kt, jvm/sql/src/main/kotlin/SqlParser.kt, jvm/sql/src/main/kotlin/SqlPlanner.kt, jvm/sql/src/main/kotlin/SqlTokenizer.kt, jvm/sql/src/main/kotlin/TokenStream.kt, jvm/sql/src/test/kotlin/SqlParserTest.kt, jvm/sql/src/test/kotlin/SqlPlannerTest.kt
SQL parser and planner now support `CAST(expr AS type)`
=> [JVM] SQL support for CAST expressions

jvm/protobuf/src/main/kotlin/ProtobufDeserializer.kt, jvm/protobuf/src/main/kotlin/ProtobufSerializer.kt, jvm/protobuf/src/test/kotlin/SerdeTest.kt, proto/ballista.proto, rust/examples/parallel-aggregate/main.rs, rust/src/cluster.rs, rust/src/serde.rs, spark/README.md, spark/settings.gradle.kts, spark/src/test/scala/org/ballistacompute/spark/TranslatePlanTest.scala
Protobuf referred to `File` rather than `Scan`
=> [Protobuf] Fix inconsistency in logical plan

rust/examples/parallel-aggregate/main.rs, rust/src/bin/executor.rs, rust/src/logicalplan.rs
Translate Ballista logical plan to DataFusion logical plan
=> [Rust] Translate Ballista logical plan to DataFusion logical plan

jvm/datatypes/src/main/kotlin/ArrowFieldVector.kt, jvm/examples/src/main/kotlin/NYCTaxi.kt, jvm/physical-plan/src/main/kotlin/expressions/ComparisonExpression.kt, jvm/physical-plan/src/main/kotlin/expressions/EqExpression.kt, jvm/physical-plan/src/test/kotlin/ComparisonExpressionTest.kt
This implements the comparison expressions more fully, with support for numeric and string types.
=> [JVM] Implement comparison expressions

jvm/datasource/src/main/kotlin/CsvDataSource.kt
Add support for all numeric types, plus null handling.
=> [JVM] CSV data source cleanup

dev/build-jvm.sh, docker/jvm-executor.dockerfile, jvm/datasource/src/main/kotlin/CsvDataSource.kt, jvm/datatypes/src/main/kotlin/ArrowFieldVector.kt, jvm/examples/src/main/kotlin/NYCTaxi.kt, jvm/execution/src/main/kotlin/ExecutionContext.kt, jvm/executor/src/main/kotlin/BallistaFlightProducer.kt, jvm/physical-plan/src/main/kotlin/expressions/CastExpression.kt, jvm/physical-plan/src/main/kotlin/expressions/MathExpression.kt, spark/src/main/scala/org/ballistacompute/spark/executor/SparkFlightProducer.scala
- Trivial optimizations to CSV reader result in an almost 2x speed increase for the integration test query
- Started to use Arrow Java correctly per the newly discovered documentation
=> [JVM] Optimizations

rust/ballista/src/dataframe.rs
translate_plan from logicalplan module is a superset of the one in dataframe, so looks like we should just reuse it.
=> remove duplicated translate_plan function in dataframe

rust/ballista/src/bin/executor.rs
The goal of this PR is to be able to send tasks to executors for execution, with results stored in memory for later retrieval.
=> [Rust] Implement do_action in Flight service

.github/workflows/jvm.yml, spark/build.gradle.kts, spark/datasource/src/main/scala/org/ballistacompute/spark/datasource/DefaultSource.java, spark/executor/src/main/scala/org/apache/spark/sql/util/ArrowUtilsHelper.scala, spark/executor/src/main/scala/org/ballistacompute/spark/executor/BallistaSparkContext.scala
This closes https://github.com/ballista-compute/ballista/issues/69
=> [JVM] Enable github actions for Spark module

rust/ballista/proto/ballista.proto, rust/ballista/src/execution/operators/hash_aggregate.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/ballista/src/execution/scheduler.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/mod.rs, rust/ballista/src/serde/to_proto.rs
Implement enough serde to start testing the scheduler mechanism for sending tasks to executors.
I will follow up with a separate PR this weekend to implement passing the pushed-down projection on parquet scans since I ran into some non-trivial issues that I need to address.
=> [Rust] Implement protobuf serde for physical plan and tasks

rust/ballista/proto/ballista.proto, rust/ballista/src/bin/executor.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/to_proto.rs, rust/examples/distributed-query/README.md
This still isn't correct, but at least removes some hard coded values from testing over the weekend and this is good enough to allow me to spin up multiple executors locally and run benchmarks.
=> Improve etcd support

rust/ballista/src/bin/executor.rs, rust/ballista/src/distributed/etcd.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/k8s.rs, rust/ballista/src/distributed/mod.rs, rust/ballista/src/execution/physical_plan.rs, rust/benchmarks/src/main.rs, rust/examples/distributed-query/README.md
Start thread to register periodically with etcd so that entry doesn't disappear after executor startup. Also improves error handling.
This closes https://github.com/ballista-compute/ballista/issues/208
=> [Rust] Improve etcd support

rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/operators/csv_scan.rs, rust/ballista/src/execution/operators/mod.rs, rust/ballista/src/execution/physical_plan.rs
Closes https://github.com/ballista-compute/ballista/issues/222
=> [Rust] Add CSV support

rust/ballista/src/dataframe.rs, rust/ballista/src/distributed/client.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/execution/operators/csv_scan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/mod.rs, rust/ballista/src/serde/to_proto.rs
Also made `to_proto` and `from_proto` more efficient by avoiding calls to clone.
=> [Rust] Bug fixes in CSV support

proto/ballista.proto, rust/ballista/proto/ballista.proto, rust/ballista/src/dataframe.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/expressions/alias.rs, rust/ballista/src/execution/expressions/avg.rs, rust/ballista/src/execution/expressions/column.rs, rust/ballista/src/execution/expressions/count.rs, rust/ballista/src/execution/expressions/max.rs, rust/ballista/src/execution/expressions/min.rs, rust/ballista/src/execution/expressions/mod.rs, rust/ballista/src/execution/expressions/sum.rs, rust/ballista/src/execution/operators/csv_scan.rs, rust/ballista/src/execution/operators/hash_aggregate.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/to_proto.rs, rust/ballista/tests/query_execution.rs, rust/examples/tpch/src/main.rs, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/Tpch.scala
```sql
+--------------+--------------+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+---------------------+
| l_returnflag | l_linestatus | sum_qty   | sum_base_price     | sum_disc_price     | sum_charge         | avg_qty            | avg_price          | avg_disc            |
+--------------+--------------+-----------+--------------------+--------------------+--------------------+--------------------+--------------------+---------------------+
| N            | O            | 764635193 | 1146548935600.9373 | 1089215873201.9028 | 1132796761431.3582 | 25.498214404372813 | 38233.85494930858  | 0.05000103682887341 |
| N            | F            | 9851614   | 14767438399.169992 | 14028805792.211416 | 14590490998.36674  | …
```
=> [Rust] TPC-H Query 1 (partial) now working

kubernetes/README.md, kubernetes/ballista-cluster-jvm.yaml, kubernetes/ballista-cluster-rust.yaml, kubernetes/ballista-cluster-spark.yaml, kubernetes/pv.yaml, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/k8s.rs, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/Tpch.scala
This PR enables a cluster to be deployed to k8s and updates the documentation.
I was not able to get TPCH query 1 fully working and will file an issue for that.
=> Partial k8s support

rust/Cargo.lock, rust/examples/distributed-query/Cargo.toml, rust/examples/distributed-query/src/main.rs
Parsing cli args simply without having to get into bringing other dependencies (like clap)
=> Adding rudimentary cli arg parsing to example

rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/expressions/comparison.rs, rust/ballista/src/execution/operators/filter.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/to_proto.rs, rust/examples/distributed-query/src/main.rs, rust/examples/tpch/src/main.rs, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/Tpch.scala
This closes https://github.com/ballista-compute/ballista/issues/251
=> [Rust] TPCH query 1 now supports filter

rust/ballista/src/execution/operators/filter.rs, rust/examples/tpch/src/main.rs, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/Tpch.scala
This closes https://github.com/ballista-compute/ballista/issues/254
=> [Rust] Fix partitioning bug in filter exec

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/benches/hash_agg.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/execution/expressions/alias.rs, rust/ballista/src/execution/expressions/avg.rs, rust/ballista/src/execution/expressions/count.rs, rust/ballista/src/execution/expressions/max.rs, rust/ballista/src/execution/expressions/min.rs, rust/ballista/src/execution/expressions/sum.rs, rust/ballista/src/execution/operators/filter.rs, rust/ballista/src/execution/operators/hash_aggregate.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/ballista/src/execution/physical_plan.rs, rust/examples/tpch/src/main.rs
- Added metrics into some operators to make it easier to debug performance issues
- Added the first cargo benchmark based on criterion
- Removed uses of `Rc<RefCell<_>>` in the aggregate accumulators
=> metrics and cargo bench

kubernetes/README.md, kubernetes/ballista-cluster-rust.yaml, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/serde/from_proto.rs
These changes allowed me to run TPCH query 1 successfully in a cluster of 12 executors running in Minikube.
=> [Rust] Kubernetes deployment now works

integration-tests/README.md, integration-tests/rust/src/main.rs
Resolves https://github.com/ballista-compute/ballista/issues/228
=> Rewriting integration tests to use flatmap over Result

.github/workflows/jvm.yml
It turns out current commands in Github Actions for JVM do not include tests. We fix this by using `gradle build` instead of `gradle assemble`
There are no test tasks in assemble dry run:
<details>
<summary>./gradlew assemble --dry-run</summary>
```
Starting a Gradle Daemon (subsequent builds will be faster)
:compileJava SKIPPED
:processResources SKIPPED
:classes SKIPPED
:jar SKIPPED
:assemble SKIPPED
:datatypes:compileKotlin SKIPPED
:datatypes:compileJava SKIPPED
:datatypes:processResources SKIPPED
:datatypes:classes SKIPPED
:datatypes:inspectClassesForKotlinIC SKIPPED
:datatypes:jar SKIPPED
:datasource:compileKotlin SKIPPED
:datasource:compileJava SKIPPED
:datasource:processResources SKIPPED
:datasource:classes SKIPPED
:datasource:inspectClassesForKotlinIC SKIPPED
:datasource:jar …
```
=> Include tests in Github Actions for JVM

rust/ballista/src/bin/executor.rs, rust/ballista/src/distributed/context.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/flight_service.rs, rust/ballista/src/distributed/mod.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/tests/query_execution.rs
This is a step towards both https://github.com/ballista-compute/ballista/issues/291 and https://github.com/ballista-compute/ballista/issues/293
=> [Rust] Refactor of scheduler and executor

rust/ballista/src/bin/executor.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/flight_service.rs, rust/ballista/src/execution/operators/filter.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/examples/tpch/src/main.rs
Executors now have fixed-size thread pool for executing tasks.
=> [Rust] Implement worker thread model in executors

rust/Cargo.lock, rust/ballista/src/distributed/client.rs, rust/ballista/src/distributed/scheduler.rs, rust/examples/tpch/Cargo.toml, rust/examples/tpch/README.md, rust/examples/tpch/src/main.rs
- TPC-H benchmark now uses structopt
- Created new stateful client for executing actions against remote executors
- Scheduler uses stateful client
=> [WIP] Saturday hacking on benchmarks

rust/examples/tpch/src/main.rs
+ [ ] The testing need to be done manually.
=> [WIP] Implement TPCH query 6

rust/Cargo.lock, rust/ballista/Cargo.toml
Oops. We were running without simd support.
=> Enable SIMD in Arrow

jvm/sql/src/main/kotlin/Expressions.kt, jvm/sql/src/main/kotlin/SqlParser.kt, jvm/sql/src/main/kotlin/SqlTokenizer.kt, jvm/sql/src/test/kotlin/SqlParserTest.kt
https://github.com/ballista-compute/ballista/issues/95
=> parse order by expression

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/benches/hash_agg.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/expressions/avg.rs, rust/ballista/src/execution/expressions/count.rs, rust/ballista/src/execution/expressions/literal.rs, rust/ballista/src/execution/expressions/max.rs, rust/ballista/src/execution/expressions/min.rs, rust/ballista/src/execution/expressions/sum.rs, rust/ballista/src/execution/operators/hash_aggregate.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/to_proto.rs
- Stop accumulating nulls
- Use FnvHashMap
- Avoid schema inference on parquet in executors
=> [Rust] Misc optimizations to HashAggregateExec

jvm/sql/src/main/kotlin/Expressions.kt, jvm/sql/src/main/kotlin/SqlParser.kt, jvm/sql/src/main/kotlin/SqlPlanner.kt, jvm/sql/src/main/kotlin/SqlTokenizer.kt, jvm/sql/src/test/kotlin/SqlParserTest.kt, jvm/sql/src/test/kotlin/SqlPlannerTest.kt, jvm/sql/src/test/kotlin/SqlTokenizerTest.kt
=> SQL Parser: Add support for HAVING

jvm/execution/src/test/kotlin/ExecutionSqlTest.kt, jvm/sql/src/main/kotlin/SqlParser.kt, jvm/sql/src/main/kotlin/SqlPlanner.kt, jvm/sql/src/main/kotlin/SqlTokenizer.kt, jvm/sql/src/main/kotlin/TokenStream.kt, jvm/sql/src/main/kotlin/Tokens.kt, jvm/sql/src/test/kotlin/SqlParserTest.kt, jvm/sql/src/test/kotlin/SqlTokenizerTest.kt
=> rewrite SqlTokenizer.kt

rust/ballista/tests/query_execution.rs
I am getting myself familiarized with the code and do clean up wherever possible.
Let me know if you want to fix it in a different way, thanks.
=> Remove unwraps used in test

rust/ballista/src/flight_service.rs
As a starting point, let's make the Rust executor capable of executing queries in-process using DataFusion.
This will let us get some integration tests and examples working again.
=> Execute queries with DataFusion

rust/Cargo.lock, rust/ballista/examples/client.rs, rust/ballista/src/bin/executor.rs, rust/ballista/src/prelude.rs, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/mod.rs
This is quick and dirty but I ran this and the client produced results, so is a starting point for more testing.
=> End-to-end example of client running query against Rust executor

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/src/bin/executor.rs, rust/ballista/src/etcd.rs, rust/ballista/src/executor.rs, rust/ballista/src/flight_service.rs
Enable running the executor in etcd mode
=> Enable etcd mode

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/mod.rs, rust/ballista/src/serde/physical_plan/to_proto.rs
Still wrapping my head around DataFusion and Ballista, so fire away with any feedback you have!
Fixes #368
=> Implement serde code for logical expressions "Not, IsNull, IsNotNull"

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/mod.rs, rust/ballista/src/serde/logical_plan/to_proto.rs
=> Implement serdes for LogicalExprNode: Negative, InList, Wildcard

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/mod.rs
Fixes https://github.com/ballista-compute/ballista/issues/373
=> Update serde code to support null literal values

rust/ballista/examples/client.rs, rust/ballista/src/bin/executor.rs, rust/ballista/src/context.rs, rust/ballista/src/executor.rs, rust/examples/tpch/src/main.rs
Get examples working against a standalone executor
=> Fix examples

docker/README.md, rust/ballista/src/columnar_batch.rs, rust/ballista/src/flight_service.rs
Some minor fixes or improvements here and there. Feel free to ask me to revert anything you don't like.
=> Misc fixes

integration-tests/rust/Cargo.lock, integration-tests/rust/Cargo.toml, rust/Cargo.lock, rust/ballista/Cargo.toml, rust/examples/tpch/Cargo.toml
Update arrow to 3.0.0 release commit
=> Update arrow to 3.0.0 release

.github/workflows/jvm.yml, .github/workflows/rust.yml, integration-tests/docker-compose.yml, integration-tests/rust/src/main.rs
currently in rust.yml because the integration test depends on docker images being created.
=> add integration-tests to rust github actions

rust/ballista/src/serde/logical_plan/from_proto.rs
Closes https://github.com/ballista-compute/ballista/issues/407
=> read file_extension when deserializing plans

rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/mod.rs
=> Implement logical_plan::from_proto for Join

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/mod.rs
This is an opinionated change, but since it was well received in the LogicalExprNode, I thought I'd do the same for LogicalPlans too.
=> Refactor LogicalPlan protobuf

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs
As far as I can tell, there's no CountDistinct aggregate function in datafusion. Maybe this is something from the past?
=> Remove CountDistinct aggregate function

rust/ballista/src/serde/logical_plan/from_proto.rs
Closes https://github.com/ballista-compute/ballista/issues/414.
=> Add support for AND, OR in serde code

benchmarks/tpch/Cargo.lock, benchmarks/tpch/Cargo.toml, benchmarks/tpch/README.md, rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/src/executor.rs
* Add snmalloc option
* Add SIMD option
* Upgrade versions
* Document usage of LTO
This should give some perf improvements on the TCPH queries.
=> Add SIMD, snmalloc options, document lto and update DataFusion

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/mod.rs, rust/ballista/src/serde/physical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/mod.rs, rust/ballista/src/serde/physical_plan/to_proto.rs
=> Implement serde for physical operator ProjectionExec

rust/ballista/src/bin/executor.rs, rust/ballista/src/executor.rs, rust/ballista/src/scheduler/standalone.rs
- Removes redundant `DiscoverMode` enum
- Partially implements `StandaloneClient`
=> Refactor scheduler code and partially implement standalone mode

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/physical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/to_proto.rs
=> Implement serde for SortExec

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/build.rs, rust/ballista/proto/ballista.proto, rust/ballista/src/bin/executor.rs, rust/ballista/src/error.rs, rust/ballista/src/executor.rs, rust/ballista/src/scheduler/etcd.rs, rust/ballista/src/scheduler/k8s.rs, rust/ballista/src/scheduler/standalone.rs, rust/ballista/src/serde/scheduler/mod.rs
Fixes #442
Once this is merged I will work on some more changes on the scheduler-client side that might be more opinionated, so I don't want to mix them with this change.
=> Implement standalone mode scheduler client

rust/ballista/proto/ballista.proto, rust/ballista/src/client.rs, rust/ballista/src/execution/planner.rs, rust/ballista/src/serde/physical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/to_proto.rs, rust/ballista/src/serde/scheduler/from_proto.rs, rust/ballista/src/serde/scheduler/mod.rs, rust/ballista/src/serde/scheduler/to_proto.rs
This PR adds more scheduler serde code and I can test up to the point of the executor receiving physical plan partitions to execute but we are missing serde implementations for some physical operators and that is blocking progress on this now.
=> WIP: Distributed query execution

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/mod.rs, rust/ballista/src/serde/physical_plan/to_proto.rs
Fixes #429 
Big thanks to @edrevo
=> HashJoinExec Serde - Physical Plan

rust/ballista/proto/ballista.proto, rust/ballista/src/client.rs, rust/ballista/src/execution/planner.rs, rust/ballista/src/flight_service.rs, rust/ballista/src/serde/physical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/to_proto.rs
Implements more of the physical plan serde, including adding support for compiling logical expressions to physical expressions by calling DataFusion.
=> Implement serde for physical plan FilterExec

rust/ballista/src/serde/physical_plan/to_proto.rs
Ref https://github.com/ballista-compute/ballista/issues/448
=> Implement serde for logical operator IsNullExpr

rust/ballista/src/serde/physical_plan/to_proto.rs
Ref https://github.com/ballista-compute/ballista/issues/448
=> Implement serde for logical operators NegativeExpr & IsNotNullExpr

rust/ballista/proto/ballista.proto, rust/ballista/src/client.rs, rust/ballista/src/executor/shuffle_reader.rs, rust/ballista/src/scheduler/planner.rs, rust/ballista/src/serde/physical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/to_proto.rs, rust/ballista/src/serde/scheduler/from_proto.rs, rust/ballista/src/serde/scheduler/to_proto.rs
Closes https://github.com/ballista-compute/ballista/issues/470
=> Implement serde for shuffle reader

rust/ballista/src/serde/physical_plan/to_proto.rs
=> Implement serde for logical operator CaseExpr

rust/ballista/src/serde/physical_plan/to_proto.rs
Ref https://github.com/ballista-compute/ballista/issues/448
=> Implement serde for logical operator InListExpr & NotExpr

rust/ballista/src/context.rs, rust/ballista/src/scheduler/mod.rs, rust/ballista/src/scheduler/planner.rs
Add error handling in the distributed planner to ensure that at least one executor is available
=> Distributed planner error handling

rust/ballista/src/serde/physical_plan/mod.rs
This PR is aimed at #494. The added test shows that deserialization of `InListExpr` and `NotExpr` for physical plans is taken care of by `compile_expr` as long as the expressions are embedded within a physical plan. Unless there is a specific requirement for implementing the direct deserialization of those expressions, I'd avoid the duplication of effort.
I'd appreciate some advice on how to proceed.
=> [WIP] from_proto for logical operator InListExpr & NotExpr

rust/ballista/src/scheduler/planner.rs
=> Make DistributedPlanner::execute_query_stage concurrent

rust/ballista/src/serde/physical_plan/mod.rs
This PR adds a test that shows serde for `PhysicalSortExpr` being handled within `SortExec`. Unless there is another place where `PhysicalSortExpr` is used, I think #519 can be closed.
=> Serde for physical sort expr

python/Cargo.lock, python/Cargo.toml, python/src/context.rs, python/src/dataframe.rs
There were several build error in python module in newest branch:
- version difference of `arrow`
- port number type
=> Fix compile error in python bind module

spark/benchmarks/README.md, spark/benchmarks/pom.xml, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/Main.scala
These benchmarks can be used to compare Ballista performance with Apache Spark.
=> Move Spark benchmarks back into this repo

rust/ballista/src/executor/collect.rs
Use the select_all stream combinator to select across a vector of
SendableRecordBatchStream
closes https://github.com/ballista-compute/ballista/issues/513
=> Make CollectExec concurrent and stream results without intermediate Vec

rust/ballista/src/serde/scheduler/from_proto.rs
This PR partially resolves #514.
=> Remove unwrap

jvm/README.md, jvm/jdbc/pom.xml, jvm/jdbc/src/main/java/org/ballistacompute/jdbc/Driver.java, jvm/jdbc/src/main/java/org/ballistacompute/jdbc/FlightConnection.java, jvm/jdbc/src/main/java/org/ballistacompute/jdbc/FlightPreparedStatement.java, jvm/jdbc/src/main/java/org/ballistacompute/jdbc/FlightResultSet.java, jvm/jdbc/src/main/java/org/ballistacompute/jdbc/FlightResultSetMetaData.java, jvm/jdbc/src/main/java/org/ballistacompute/jdbc/FlightStatement.java, jvm/jdbc/src/main/java/org/ballistacompute/jdbc/ResultSetHelper.java, jvm/jdbc/src/main/resources/META-INF/services/java.sql.Driver, jvm/jdbc/src/test/java/org/ballistacompute/jdbc/DriverTest.java, jvm/jdbc/src/test/java/org/ballistacompute/jdbc/ResultSetHelperTest.java, jvm/pom.xml
Moving the JDBC driver prototype back into the main repo. It doesn't work at all and needs updating and adding to integration tests.
=> Add JDBC Driver (WIP)

.github/workflows/check-license.yml, .github/workflows/rust.yml, .gitignore, dev/ci/check-asl-header.py, python/ballista/__init__.py, python/ballista/__init__.pyi, python/ci/check_stub_exhaustiveness.py, python/examples/testquery.py, python/tests/__init__.py, python/tests/test_simple.py, rust/ballista/src/bin/scheduler.rs, rust/ballista/src/columnar_batch.rs, rust/ballista/src/scheduler/execution_plans/mod.rs, rust/ballista/src/scheduler/execution_plans/unresolved_shuffle.rs, rust/ballista/src/scheduler/state/mod.rs
We want to make sure that all code contributions include the ASL license header.
Closes https://github.com/ballista-compute/ballista/issues/160
=> Add CI check for ASL header

rust/ballista/src/client.rs, rust/ballista/src/context.rs, rust/ballista/src/scheduler/execution_plans/shuffle_reader.rs
Closes https://github.com/ballista-compute/ballista/issues/601
=> Make ShuffleReader streaming

rust/ballista/src/client.rs
**Description**
Modify execute_action to stream results instead of loading all results into a Vec. Not totally sure whether this is implemented as the TODO intended it to be so feel free to suggest any changes.
**Testing Done**
Ran TPCH queries as documented [https://github.com/ballista-compute/ballista/blob/main/rust/benchmarks/tpch/README.md](here) (1GB dataset) on my laptop with 1 scheduler + 3 executors and saw similar results in each (with high enough variance that maybe any real differences probably aren't detectable with my current setup).
I haven't gotten the docker setup to build on my laptop so I didn't run any of the docker based tests.
Before changes:
```
Query 1 avg time: 3472.13 ms
Query 3 avg time: 3435.16 ms
Query 5 avg time: 3431.22 ms
Query 6 avg time: 2901.66 ms
Query …
```
=> Modify execute_action to stream results

rust/executor/src/execution_loop.rs, rust/executor/src/main.rs, rust/lib/src/serde/physical_plan/to_proto.rs
=> Executor control how many concurrent tasks run 

rust/Cargo.lock, rust/lib/Cargo.toml, rust/lib/src/executor/flight_service.rs
To avoid the same blocking problems we saw in DataFusion, I'm removing crossbeam from the project (there was only one usage)
=> Remove crossbeam

rust/lib/src/utils.rs
This is a starting point for generating query plan diagrams for use in the Web UI.
[Example diagram (PDF)](https://github.com/ballista-compute/ballista/files/6095528/q1.pdf)
=> Add utility for generating query plan diagrams in DOT format

rust/executor/src/execution_loop.rs
Fixes what @edrevo wrote on #623
Ref https://github.com/ballista-compute/ballista/pull/623#discussion_r588206608
=> Save redundant clones

rust/core/proto/ballista.proto, rust/core/src/serde/logical_plan/from_proto.rs, rust/core/src/serde/logical_plan/to_proto.rs, rust/core/src/serde/physical_plan/from_proto.rs, rust/core/src/serde/physical_plan/to_proto.rs
I'm working on implementing shuffle hash join and found that this serde code was missing,
=> Implement serde for RepartitionExec physical operator
