ballista-compute/ballista

examples/nyctaxi/README.md, examples/nyctaxi/templates/executor.yaml
This PR adds ingress so that query plans can be sent directly to executor nodes from outside the cluster, as a step towards being able to run examples in "client mode" (using Apache Spark terminology).
=> Add ingress

examples/nyctaxi/README.md
This is required so that minikube can access the data, since minikube is
running inside a VM.
=> Update example instructions to include 'minikube mount'

docker/Dockerfile.binary
[tini][] provides better signal handling for free, so containers should
stop quickly upon termination. Using alpine also means we can get
a shell in the pods for debugging!
[tini]: https://github.com/krallin/tini
=> Use Alpine Linux for server image; add tini

jvm/sql/src/main/kotlin/SqlTokenizer.kt, jvm/sql/src/test/kotlin/SqlTokenizerTest.kt
- Expands SQLTokenizer tests by mirroring many of the tests from the SQLParer.
- Add basic tests for LiteralDoubleToken, LiteralLongToken.
- Add support for compound operators.
- Add test for compound operators.
There's more changes I'd like to make to the tokenizer to make it more robust, but thought this would be a good way to get introduced into the project.
My only question at the moment is: Is there a particular SQL implementation the Tokenizer should aim to support?
=> Kotlin: Update SQL Tokenizer for Comparison Operators

benchmarks/Cargo.lock, benchmarks/src/main.rs, dev/build-rust.sh, docker/jvm-benchmarks.dockerfile, docker/rust-base.dockerfile, docker/rust-benchmarks.dockerfile, docker/rust-cached-deps.dockerfile, docker/rust-executor.dockerfile, integration-tests/rust/Cargo.lock, integration-tests/rust/src/main.rs, jvm/benchmarks/src/main/kotlin/Benchmarks.kt, jvm/examples/src/main/kotlin/NYCTaxi.kt, jvm/examples/src/main/kotlin/ParallelQuery.kt, jvm/execution/src/main/kotlin/ExecutionContext.kt, jvm/execution/src/test/kotlin/ExecutionSqlTest.kt, jvm/execution/src/test/kotlin/ExecutionTest.kt, jvm/execution/src/test/kotlin/ReadmeExamplesTest.kt, jvm/executor/src/main/kotlin/BallistaFlightProducer.kt, rust/benchmarks/Cargo.lock, rust/benchmarks/Cargo.toml, rust/benchmarks/run-native.sh, rust/benchmarks/src/main.rs, rust/examples/parallel-aggregate/main.rs, rust/examples/parallel-aggregate/parallel-aggregate-rs.yaml, rust/src/dataframe.rs, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/Benchmarks.scala
- Rust docker images now use debian:buster-slim and images are 89 MB
- CSV batch size is configurable
- Fixed bug in JVM flight producer
=> Various benchmarking and packaging improvements

rust/ballista/src/error.rs
std::error::Error trait makes it much easier for caller to propagate the error.
=> implement std::error::Error for BallistaError

.github/workflows/rust.yml
This fixes up the build so that it builds for three platforms: Linux Ubuntu, Mac OS X, and Windows.  Windows was a little bit of a red-headed step-child since it requires the use of `vcpkg` to install the openssl library.  This increases the build time by about 2.5x, unfortunately.
=> Workflow improvement for GitHub Workflows

integration-tests/rust/Cargo.lock, integration-tests/rust/Cargo.toml, integration-tests/rust/src/main.rs, rust/Cargo.lock, rust/ballista/Cargo.toml
Recent change to use CsvReadOptions caused integration tests to fail to compile (we don't have github actions set up to build that crate yet).
=> [Rust] Fix integration tests

.github/workflows/rust.yml
The build was a little more complicated than I expected.  While it was suggested that vcpkg be cloned and installed, turns out, GitHub already has the tools pre-installed.  This new update takes advantage of this, updating the library for the build, and addressing an issue with `rustfmt` on Windows.  It also tweaks the names of each build step so that it is more clear in the Actions page as to what is happening.
=> Issue 159: Windows builds failing with vcpkg error

rust/ballista/src/bin/executor.rs, rust/ballista/src/client.rs, rust/ballista/src/dataframe.rs, rust/ballista/src/execution_plan.rs, rust/ballista/src/lib.rs, rust/ballista/src/logical_plan.rs, rust/ballista/src/physical_plan.rs, rust/ballista/src/plan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/mod.rs, rust/ballista/src/serde/to_proto.rs
In order to be able to execute distributed queries, we need a physical plan with support for distributed operations such as shuffles. This PR adds those data structures based on the equivalents defined in Apache Spark.
=> [Rust] Create data structures for physical plan

proto/ballista.proto, rust/Cargo.lock, rust/Cargo.toml, rust/ballista/proto/ballista.proto, rust/ballista/src/bin/executor.rs, rust/ballista/src/execution/filter.rs, rust/ballista/src/execution/parquet_scan.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/execution/projection.rs, rust/ballista/src/execution/scheduler.rs, rust/ballista/src/execution/shuffle_exchange.rs, rust/ballista/src/execution/shuffle_reader.rs, rust/ballista/src/execution/shuffled_hash_join.rs, rust/examples/distributed-query/Cargo.toml, rust/examples/distributed-query/README.md, rust/examples/distributed-query/src/main.rs
This PR introduces a basic scheduler capable of create a Job definition (DAG of stages) from a physical query plan.
Example:
```
Job 15aeb081-e515-44fa-a02c-6c5e3c59d16e has 2 stages:
Stage 0:
Stage 0 depends on stages [1].
HashAggregate: mode=Final, groupExpr=[#passenger_count], aggrExpr=[SUM(#fare_amount)]
ShuffleReader: stage_id=1
Stage 1:
Stage 1 has no dependencies.
HashAggregate: mode=Partial, groupExpr=[#passenger_count], aggrExpr=[SUM(#fare_amount)]
ParquetScan: "/mnt/nyctaxi/parquet/year=2019", partitions=12
```
It also lays some groundwork in defining the physical plan in protobuf format.
=> Implement basic scheduler to create Job (DAG of stages) from a physical query plan

.github/workflows/rust.yml
There is no need to run clippy on different platforms
=> move linting logic into separate job to reduce CI runtime

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/src/datagen.rs, rust/ballista/src/execution/in_memory.rs, rust/ballista/src/execution/mod.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/lib.rs, rust/ballista/tests/query_execution.rs
Use a data generator instead of reading from Parquet to simplify CI and also make it easier to test performance of hash agg independently of file io.
Also adds InMemoryTableScanExec.
=> [Rust] Integration test for hash agg using data generator

rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/ballista/src/serde/from_proto.rs, rust/examples/distributed-query/README.md
- Use a bounded channel in ParquetScanExec to manage memory pressure better
- Fix a bug with an unwrap that was inadvertently introduced
- Move hard-coded batch sizes higher up .. eventually needs to be in a config
=> Misc improvements

rust/ballista/src/execution/operators/filter.rs, rust/ballista/tests/query_execution.rs
Closed #184.
Note that this currently fails the tests because we have not implemented comparison operators:
```
thread 'hash_aggregate_with_filter' panicked at 'called `Result::unwrap()` on an `Err` value: General("Unsupported binary operator GtEq")', ballista/tests/query_execution.rs:56:9
```
We need to push for that before this one.
=> Added support to filters.

proto/ballista.proto, rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/benches/hash_agg.rs, rust/ballista/proto/ballista.proto, rust/ballista/src/dataframe.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/expressions/alias.rs, rust/ballista/src/execution/expressions/arithmetic.rs, rust/ballista/src/execution/expressions/avg.rs, rust/ballista/src/execution/expressions/column.rs, rust/ballista/src/execution/expressions/comparison.rs, rust/ballista/src/execution/expressions/count.rs, rust/ballista/src/execution/expressions/literal.rs, rust/ballista/src/execution/expressions/max.rs, rust/ballista/src/execution/expressions/min.rs, rust/ballista/src/execution/expressions/sum.rs, rust/ballista/src/execution/operators/csv_scan.rs, rust/ballista/src/execution/operators/filter.rs, rust/ballista/src/execution/operators/hash_aggregate.rs, rust/ballista/src/execution/operators/in_memory.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/ballista/src/execution/operators/projection.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/mod.rs, rust/ballista/src/serde/to_proto.rs, rust/ballista/src/utils/datagen.rs, rust/ballista/tests/query_execution.rs
This migrates the code base to align with master from arrow.
Note that I have only validated that the tests pass, and assumed that this was a sufficient condition. However, looking at the tests themselves, this may not be sufficient.
This removes two columns from `ballista.proto`.
=> Migrate to latest arrow

jvm/logical-plan/src/test/kotlin/LogicalPlanTest.kt, jvm/protobuf/src/main/kotlin/ProtobufDeserializer.kt, jvm/protobuf/src/main/kotlin/ProtobufSerializer.kt, proto/ballista.proto, rust/ballista/proto/ballista.proto, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/operators/csv_scan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/to_proto.rs
The original problem of failing integration test #261 was a symptom to several issues.
Integration test failed because type of `passenger_count` column was `Int64` instead of `Int32` which was provided in schema. This happened because CSV schema (along with some other options) was not actually serialized to protobuf before sending query to the executor. The executor infered schema instead and this is the source of `Int64` type in the result.
The second issue is that even though the projection parameter is optional in the plan description, it is serialized as repeated filed in protobuf message `ScanNode`. Repeated fields cannot be optional, so empty array was sent to the executor as the projection. This resulted in empty result from CSV scan because empty projection simply means "the user …
=> Respect schema and projection parameters from client

.github/workflows/rust.yml
The image tag is currently "echo" due to a mistake in a previous commit. This fixes it.
=> Fixed error in building docker image tag.

dev/download-nyctaxi-files.sh, dev/split-csv.sh, kubernetes/README.md, kubernetes/ballista-cluster.yaml, kubernetes/populate-data.yaml, kubernetes/rbac.yaml
The aim of this PR is to have a simple configuration that new users can use to deploy Ballista on a generic kubernetes cluster.
There are two main differences between a generic k8 and minikube from the current deployment's perspective:
* docker images must be pulled from somewhere (and not just built)
* files must be dumped in persistent volumes (and not just mounted)
This commit:
* Adds a yaml with a job to populate the data to the persistent volume, so that we do not rely on local mounts
* Adds a yaml configuration that:
* has a `imagePullSecrets` to kubernetes be able to pull images from github.
* uses the image `docker.pkg.github.com/ballista-compute/ballista/ballista-rust:main`, so that when this code is pulled from `main`, that is also the image that is deployed on kubernetes
* …
=> Refactored kubernetes guide to support a remote cluster

rust/ballista/Cargo.toml, rust/ballista/benches/hash_agg.rs, rust/ballista/src/execution/operators/hash_aggregate.rs, rust/ballista/tests/query_execution.rs
- Remove unnecessary use of thread and channel from HashAggregateExec
- Implement micro-benchmark for HashAggregateExec
The micro-benchmark showed a 68% improvement but TPCH is no faster.
=> [WIP] Hash Aggregate Performance

dev/split-csv.sh, kubernetes/README.md, kubernetes/populate-data.yaml
I was able to deploy a cluster to EKS using these instructions but I couldn't figure out where the files were downloaded and couldn't get the example to run. I made some changes to change the path from `/mnt/nztaxi.csv` to `/mnt/nyctaxi/csv` for consistency with other published documentation, blog posts, demos, etc and will try again once this is merged to main.
=> Small improvements to k8s docs

integration-tests/rust/Cargo.lock, integration-tests/rust/src/main.rs, proto/ballista.proto, rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/proto/ballista.proto, rust/ballista/src/dataframe.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/operators/csv_scan.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/to_proto.rs, rust/examples/apache-spark-rust-bindings/src/main.rs, rust/examples/distributed-query/src/main.rs, rust/examples/tpch/src/main.rs
- Perform file scan once in scheduler instead of in each parquet scan exec instance
- Use async channel
- Minor DataFrame API cleanup
- Make file format configurable in TPC-H example
=> Parquet performance

proto/ballista.proto, rust/ballista/benches/hash_agg.rs, rust/ballista/proto/ballista.proto, rust/ballista/src/dataframe.rs, rust/ballista/src/distributed/executor.rs, rust/ballista/src/distributed/scheduler.rs, rust/ballista/src/execution/operators/csv_scan.rs, rust/ballista/src/execution/operators/filter.rs, rust/ballista/src/execution/operators/hash_aggregate.rs, rust/ballista/src/execution/operators/in_memory.rs, rust/ballista/src/execution/operators/parquet_scan.rs, rust/ballista/src/execution/operators/projection.rs, rust/ballista/src/execution/physical_plan.rs, rust/ballista/src/serde/from_proto.rs, rust/ballista/src/serde/to_proto.rs, rust/ballista/tests/query_execution.rs, rust/examples/tpch/src/main.rs
Remove `async` from `ColumnBatchIter` so we can remove the separate threads for parquet scans.
=> [Rust] Remove async from ColumnBatchIter

rust/ballista/Cargo.toml
specify ref for arrow dependency git repository to avoid cargo build failed
=> specify ref for arrow dependency git repository

spark/README.md, spark/benchmarks/Dockerfile, spark/benchmarks/README.md, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/Main.scala, spark/benchmarks/src/main/scala/org/ballistacompute/spark/benchmarks/tpch/Tpch.scala
This PR simply adds a CLI to the Spark benchmark code and removes the hard-coded ad-hoc code that I had been running manually from my IDE. It also updates the Docker packaging so that others can run the benchmarks and TPC-H file conversion by just pulling the published Docker image.
=> Add CLI to Spark benchmark

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/src/error.rs, rust/ballista/src/lib.rs, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/mod.rs, rust/ballista/src/serde/physical_plan/to_proto.rs
The main goal of this PR is to add a unit test for round-trip serde for a simple logical plan.
Other changes made to support this:
- Ported the `error.rs` file from the original codebase
- Updated the serde code to use `BallistaError` instead of `BallistaProtoError`
=> unit test for serde of logical plan

CONTRIBUTING.md
Text is copy&paste from https://andygrove.io/2021/01/ballista-2021/, but added mention to Etcd since I believe K8s isn't the only resource manager that should be supported in the long term.
=> Add project goals to CONTRIBUTING

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/src/bin/executor.rs, rust/ballista/src/lib.rs, rust/ballista/src/serde/mod.rs
The Rust executor runs again, but any requests will result in an error response.
```bash
cargo run --color=always --package ballista --bin executor
Finished dev [unoptimized + debuginfo] target(s) in 0.13s
Running `target/debug/executor`
Ballista v0.4.0-SNAPSHOT Rust Executor listening on 0.0.0.0:8000
```
=> Re-instate Rust executor

rust/ballista/src/client.rs, rust/ballista/src/lib.rs, rust/ballista/src/serde/scheduler/mod.rs, rust/ballista/src/serde/scheduler/to_proto.rs
Adds client code that is capable of serializing a logical query plan and sending it to an executor and then receiving the results.
=> Port client from old code

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/mod.rs
Hi, I took a crack at implementing Serde for LogicalPlan::Sort. I assumed that ballista.proto needed to be changed, I'm not sure about the protobuf field numbering as there is the jump from one byte to 2 when exceeding 15 fields and I wasn't sure if the lower numbers were being reserved common node types. If this looks alright I'll take a crack at the other node types.
=> Implemented Serde for SortNode

rust/ballista/build.rs, rust/ballista/proto/ballista.proto, rust/ballista/src/flight_service.rs, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/mod.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/mod.rs
Implemented serde for the LogicalPlan nodes repartition, create external table, empty relation, and explain. I'm a little unsure about the create external table implementation because as far as I could tell none of the other node types  serialize their schema and I couldn't find a way around serializing it for this node.  
Some smaller changes made:
1.  Changed [build.rs](rust/ballista/build.rs) so it is only run when [ballista.proto](rust/ballista/proto/ballista.proto) is changed. I also changed from a panic to returning a result as I was finding the stack traces were  noise when changing the protobuf definition.
2.  Moved logical plan roundtrip tests to [src/serde/logical_plan/mod.rs](rust/ballista/src/serde/logical_plan/mod.rs).
=> Logical plan node serde implementation

docs/dev-env-rust.md
Hello,
I'm setting up the dev environment by following the guide, and found protobuf installation was missing.
Please check~
=> Add protobuf installation in rust env guide

.github/workflows/rust.yml
Added a rust code formatting check to CI. 
Added job dependency so that tests run only after lints and formatting checks pass. I wasn't sure what the Docker job does so i didn't change it.
Added rule to only run rust CI when a file in rust/ is changed.
It might be worth it to check a rustfmt.toml file into the repo just to make sure that there aren't any formatting inconsistencies between contributor configurations.
=> Added rust code formatting check to CI. Closes #364 

rust/ballista/src/lib.rs, rust/ballista/src/shuffle_hash_join.rs, rust/ballista/src/shuffle_write.rs
This PR starts to implement some experimental code for ShuffleHashJoinExec / ShuffleWriteExec in preparation for supporting distributed query execution.
=> Exploratory work on ShuffleHashJoinExec / ShuffleWriteExec

rust/ballista/proto/ballista.proto, rust/ballista/src/serde/logical_plan/from_proto.rs, rust/ballista/src/serde/logical_plan/mod.rs, rust/ballista/src/serde/logical_plan/to_proto.rs
I wasn't sure how to deal with the `DataType` <> `ArrowType` conversion for the `Cast` operator, since it looks like
(per https://github.com/apache/arrow/blob/master/rust/arrow/src/compute/kernels/cast.rs#L51) there are many
types of casts that are possible that weren't representable with the currently serializable types. I didn't want to change the
proto `ArrowType` in this PR, so I only added types to `from_proto_arrow_type`/`to_proto_arrow_type` that didn't have size
params.
Fixes #369, #370, #371, #372
=> Implement serdes for LogicalExprNode: Between, Case, Cast, Sort

rust/ballista/src/serde/logical_plan/mod.rs
Apparently in https://github.com/ballista-compute/ballista/pull/379 I missed that there were unit tests for logical expressions. Adding them here.
=> Add missing tests

rust/ballista/src/etcd.rs
Since this method is called through `tokio::spawn`, using `thread::sleep` isn't a great idea since it will completely block one of tokio's threads in its threadpool. By using tokio's version of sleep (called delay_for in tokio 0.2 but called sleep in tokio 1.0), the thread can handle other tasks while the etcd loop is idle.
=> Use async sleep to avoid blocking thread

kubernetes/populate-data.yaml
Fix so pod restarts on minikube will pull the data in again and will not fail to download data after a first failure.
=> Simple fix to make populate-data atomic

rust/ballista/src/bin/executor.rs, rust/ballista/src/executor/flight_service.rs, rust/ballista/src/executor/mod.rs, rust/ballista/src/utils.rs
This PR implements FetchPartition in the executor. The implementation needs some improvements but this should be enough to enable end to end testing.
=> Implement FetchPartition in executor

rust/ballista/examples/planner.rs, rust/ballista/src/executor/flight_service.rs, rust/ballista/src/executor/query_stage.rs, rust/ballista/src/scheduler/planner.rs
The example query gets transformed into this query plan:
```
QueryStageExec { job_uuid: c20cd182-2792-457b-a4d0-a24b0939b
ProjectionExec { expr: [(Column { name: "l_shipmode" }, "l_s
CoalesceBatchesExec { input: HashJoinExec { left: QueryStage
HashJoinExec { left: QueryStageExec { job_uuid: c20cd182-279
QueryStageExec { job_uuid: c20cd182-2792-457b-a4d0-a24b0939b
CsvExec { path: "/home/andy/git/ballista/benchmarks/tpch/dat
QueryStageExec { job_uuid: c20cd182-2792-457b-a4d0-a24b0939b
CsvExec { path: "/home/andy/git/ballista/benchmarks/tpch/dat
```
The two leaf node query stages get executed against the executors and the next query stage looks like this:
```
ProjectionExec { expr: [(Column { name: "l_shipmode" }, "l_s
CoalesceBatchesExec { input: HashJoinExec { left: ShuffleRea
HashJoinExec …
```
=> WIP: Implement more functionality in the distributed query planner

dev/build-rust.sh, rust/ballista/Cargo.toml
Closes https://github.com/ballista-compute/ballista/issues/495
I suspect the cached docker layers had old versions of crates that somehow were being picked up in the build. This PR is a quick fix but isn't ideal since it will be really slow to build the docker image now.
```bash
h$ docker-compose up
WARNING: Found orphan containers (tpch_ballista-rust_1, tpch_scheduler_1, tpch_executor_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting tpch_etcd_1 ... done
Recreating tpch_ballista-scheduler_1 ... done
Recreating tpch_ballista-executor_1  ... done
Attaching to tpch_etcd_1, tpch_ballista-scheduler_1, tpch_ballista-executor_1
ballista-executor_1   | [2021-02-11T15:04:38Z INFO …
```
=> Use --no-cache when building Docker image

rust/Cargo.lock, rust/ballista/Cargo.toml, rust/ballista/proto/ballista.proto, rust/ballista/src/serde/physical_plan/from_proto.rs, rust/ballista/src/serde/physical_plan/mod.rs, rust/ballista/src/serde/physical_plan/to_proto.rs, rust/benchmarks/tpch/Cargo.toml
This PR fixes two bugs:
1. We were not persisting the names for the group by expressions
2. We needed to persist the input schema before any aggregates are applied
This depends on https://github.com/apache/arrow/pull/9481
Closes https://github.com/ballista-compute/ballista/issues/504
```
Running benchmark with query 12:
select
l_shipmode,
sum(case
when o_orderpriority = '1-URGENT'
or o_orderpriority = '2-HIGH'
then 1
else 0
end) as high_line_count,
sum(case
when o_orderpriority <> '1-URGENT'
and o_orderpriority <> '2-HIGH'
then 1
else 0
end) as low_line_count
from
lineitem
join
orders
on
l_orderkey = o_orderkey
where
l_shipmode in ('MAIL', 'SHIP')
and l_commitdate < l_receiptdate
and l_shipdate < l_commitdate
and l_receiptdate >= date '1994-01-01'
and l_receiptdate < date '1995-01-01' …
```
=> Fix HashAggregateExec

.dockerignore, dev/build-rust-base.sh, dev/build-rust.sh, docker/rust-base.dockerfile, docker/rust.dockerfile
This PR splits the Dockerfile into two parts:
1 rust-base.Dockerfile which contains Rust and no Ballista components. This Dockerfile changes rarely and I have pushed a tagged version to Dockerhub
2. Ballista Rust image which extends the base image
=> Docker refactor

.github/workflows/rust.yml, dev/integration-tests.sh, docs/integration-testing.md, rust/ballista/src/scheduler/mod.rs, rust/benchmarks/tpch/README.md, rust/benchmarks/tpch/docker-compose.yaml, rust/benchmarks/tpch/src/main.rs
To run integration tests locally:
```bash
./dev/integration-tests.sh
```
Note that for now it is necessary to have write access to `/data` on the local file system until https://github.com/ballista-compute/ballista/issues/473 is resolved.
=> Add integration test script

README.md
The README's link to the TPC-H benchmarks is broken. Perhaps it went stale after Rust code was moved into the `rust/` subdirectory.
This updates the link. Additionally, it uses relative link syntax, which should be invariant to branch/commit.
=> README TPC-H benchmark link fix

dev/integration-tests.sh, rust/benchmarks/tpch/README.md, rust/benchmarks/tpch/docker-compose.yaml, rust/benchmarks/tpch/run.sh
Not the best solution, since it involves compiling tpch on every run, but it beats having a broken docker-compose.
Fixes #530
=> Fix tpch in docker-compose

rust/ballista/src/serde/logical_plan/mod.rs, rust/ballista/src/serde/logical_plan/to_proto.rs, rust/ballista/src/serde/physical_plan/to_proto.rs
Addresses #518.
Refactors matching logic into `TryInto<protobuf::ScalarFunction> for &BuiltinScalarFunction` and uses this in both logical and physical serialization of scalar functions.
Adds a roundtrip test for `sqrt` to check implementation.
_Note: Couldn't run integration test on Mac OSX, will have to finish #473 for that._
=> Implement logical to_proto for ScalarFunction

rust/ballista/src/client.rs, rust/ballista/src/executor/flight_service.rs, rust/ballista/src/serde/scheduler/from_proto.rs, rust/ballista/src/serde/scheduler/mod.rs, rust/ballista/src/serde/scheduler/to_proto.rs, rust/ballista/src/utils.rs
This reduces memory overhead a bit by avoiding copying all the batches into a vec twice - now it only does it once. Still not great.
Also:
- Refactors the code in preparation for streaming
- Removes the legacy code for executors executing queries in-process with DataFusion
=> Refactor in preparation for streaming

rust/ballista/src/executor/flight_service.rs, rust/ballista/src/scheduler/planner.rs, rust/ballista/src/utils.rs
This is  a bit more concise now:
```
[2021-02-15T19:09:25Z INFO  ballista::scheduler::planner] execute_query_stage() stage_id=2
MergeExec
QueryStageExec: job=411e79af-8b0c-4705-9e39-c14452b8c7ed, stage=1
HashAggregateExec: groupBy=["l_returnflag", "l_linestatus"], aggrExpr=["SUM(l_quantity) [\"l_quantity\"]", "SUM(l_extendedprice) [\"l_extendedprice\"]", "SUM(l_extendedprice Multiply Int64(1) Minus l_discount) [\"l_extendedprice * CAST(1 AS Float64) - l_discount\"]", "SUM(l_extendedprice Multiply Int64(1) Minus l_discount Multiply Int64(1) Plus l_tax) [\"l_extendedprice * CAST(1 AS Float64) - l_discount * CAST(1 AS Float64) + l_tax\"]", "AVG(l_quantity) [\"l_quantity\"]", "AVG(l_extendedprice) [\"l_extendedprice\"]", "AVG(l_discount) [\"l_discount\"]", "COUNT(UInt8(1)) [\"1\"]"] …
```
=> Improve debug formatting of physical plans

docker/rust.dockerfile
This enables the snmalloc feature, addressesing a part of https://github.com/ballista-compute/ballista/issues/549
enabling simd would require a nightly rust. 
I couldn't yet figure out how to do lto, as it is not directly building a binary with the current setup. "error: lto can only be run for executables, cdylibs and static library outputs". I think we only want to have lto enabled on the executor.
=> Add snmalloc feature to docker image

rust/ballista/src/client.rs, rust/ballista/src/executor/flight_service.rs, rust/ballista/src/scheduler/planner.rs, rust/ballista/src/serde/scheduler/mod.rs, rust/ballista/src/utils.rs
Addresses #557
So far I have stats being returned in the ExecutePartitionResult object. I am not sure how the scheduler should be maintaining state, but I would love to hear thoughts. 
Not sure of the best way to test this. Going to see how it does in CI. 
I may look into writing some integration testing infrastructure in general for Ballista, but not for this issue as it is blocking #563.
=> first pass at returning partition stats to scheduler

rust/ballista/proto/ballista.proto, rust/ballista/src/client.rs, rust/ballista/src/context.rs, rust/ballista/src/executor/flight_service.rs, rust/ballista/src/scheduler/planner.rs, rust/ballista/src/serde/scheduler/from_proto.rs, rust/ballista/src/serde/scheduler/mod.rs, rust/ballista/src/serde/scheduler/to_proto.rs, rust/ballista/src/utils.rs
With this change, the planner divides partitions up between the available executors and then sends one ExecutePartition request per executor, with a list of partitions to execute.
This makes a huge difference in the case of HashJoinExec, where each instance of the operator will execute the left side once and fetch all the results into RAM. Before this change, this work would happen once per partition, and now it happens once per executor.
I have been able to run a benchmark against SF=100 for the first time since the rewrite. :tada: 
```
Running benchmarks with the following options: BenchmarkOpt { host: "localhost", port: 50050, query: 5, debug: false, iterations: 1, batch_size: 32768, path: "/mnt/tpch/parquet-sf100-partitioned/", file_format: "parquet" }
Running benchmark with query 5: …
```
=> Support executing multiple partitions in calls to ExecutePartition

rust/ballista/proto/ballista.proto, rust/ballista/src/context.rs, rust/ballista/src/scheduler/mod.rs
Changes `ExecuteLogicalPlan` to `ExecuteQuery` and allows plain SQL strings in addition to logical plans as described in #567.
New to both Rust and the project, any guidance on better/more idiomatic code very welcome.
=> ExecuteLogicalPlan  ->  ExecuteQuery  and allow plain SQL

rust/ballista/src/scheduler/planner.rs
This is a critical bug fix to support multiple executors.
Closes https://github.com/ballista-compute/ballista/issues/603
=> Bug fix: support multiple executors

rust/scheduler/src/main.rs
Hi, 
I was launching the scheduler from cargo and i saw the `println!` of the of  the namespace
```
❯ cargo run --bin ballista-scheduler                                                                                                                                                                             
Finished dev [unoptimized + debuginfo] target(s) in 0.10s
Running `target/debug/ballista-scheduler`
ballista
[2021-03-03T21:04:23Z INFO  ballista_scheduler] Ballista v0.4.2-SNAPSHOT Scheduler listening on 0.0.0.0:50050
```
I'm not sure if it's needed. In case not, this PR removes it :)
=> println removal in scheduler main

docker/rust.dockerfile, rust/Cargo.toml
https://github.com/ballista-compute/ballista/issues/592
Just putting it in the workspace works nicely.
Will do some comparison in benchmarking later, and maybe test with codegen units =1 too
=> Build binaries with --release with lto by default

docker/rust.dockerfile
The non-snmalloc binary was being built after the snmalloc binary, thus ending with a lower performance executor
=> Fix dockerfile

rust/lib/src/scheduler/mod.rs
Adds some more debug logging for showing optimized plan being created in Ballista.
This can help with identifying suboptimal logical plans.
Another change is to log millis instead of seconds in physical plan creation (>= 500ms would be very slow already)
Looks like this:
```
ballista-scheduler_1   | [2021-03-05T22:35:10Z DEBUG ballista::scheduler] Calculated optimized plan: Sort: #l_returnflag ASC NULLS FIRST, #l_linestatus ASC NULLS FIRST
ballista-scheduler_1   |       Projection: #l_returnflag, #l_linestatus, #SUM(l_quantity) AS sum_qty, #SUM(l_extendedprice) AS sum_base_price, #SUM(l_extendedprice Multiply Int64(1) Minus l_discount) AS sum_disc_price, #SUM(l_extendedprice Multiply Int64(1) Minus l_discount Multiply Int64(1) Plus l_tax) AS sum_charge, #AVG(l_quantity) AS avg_qty, …
```
=> Add debug logging for optimized plan

rust/Cargo.toml, rust/core/proto/ballista.proto, rust/core/src/client.rs, rust/core/src/serde/scheduler/from_proto.rs, rust/core/src/serde/scheduler/mod.rs, rust/core/src/serde/scheduler/to_proto.rs, rust/core/src/utils.rs, rust/executor/src/flight_service.rs, rust/scheduler/src/planner.rs, rust/scheduler/src/state/mod.rs
Changes in this PR:
- Add `PartitionStats` and `ColumnStats` to protobuf and implement serde code
- Distributed planner now stores partition stats from executed query stages
- Removes `null_count` that I had previously added in `PartitionStats`. This is a column-level statistic not a partition-level statistic so we should add it back once we implement column stats.
=> Implement partition statistics

python/Cargo.lock, python/Cargo.toml, python/src/expression.rs, python/src/functions.rs, rust/Cargo.lock, rust/benchmarks/tpch/Cargo.toml, rust/client/Cargo.toml, rust/core/Cargo.toml, rust/core/proto/ballista.proto, rust/core/src/serde/logical_plan/from_proto.rs, rust/core/src/serde/logical_plan/to_proto.rs, rust/executor/Cargo.toml, rust/scheduler/Cargo.toml
* Update arrow to get in some new features / fixes / performance improvements
* Upgrade sqlparser to match upstream (0.8)
* Rename length -> OctetLength//Octetlength
*  change a type in the python bindings
=> Update arrow to 46161d2

.dockerignore, docker/rust.dockerfile, rust/benchmarks/tpch/run.sh
Copy compiled tpch into ballista docker image to avoid recompiling something that was already compiled
=> Simplify integration tests
